### ISSUE TITLE
Will you consider adding prefix, e.g. "rs_" or "Aul_"?

### ISSUE THREAD

**Issue by PeterLinBiz** [rsoesemann/apex-unified-logging#5]
Hi Robert,

Thank you for this great apex-unified-logging repository and converting it into Salesforce DX Source format!

I believe that more and more teams will implement this Log.cls into their Production Org using Unlocked Package.

As you may already know, AEP team used prefix "fflib_", e.g. fflib_SObjectUnitOfWork.cls in its repositories, e.g. https://github.com/apex-enterprise-patterns/fflib-apex-common .

Will you consider adding a prefix, e.g. "rs_", "rslib_" or "Aul_"?
For example:
rs_Log.cls / Aul_Log.cls
rs_Log__e / Aul_Log__e
rs_Settings__c / Aul_Settings__c

I understood that it is a hard decision to refactor this repository with a prefix e.g. "rs_" with 43 forks. And the fflib-apex-common has 379 forks.

My Production Org happens to have no Log.cls, Log__e or Settings__c. I am about to create this as a Unlocked Package, but debating with myself of whether I should refactor this with a "rs_" prefix.

It seemed to me that if you decide to refactor this V1.0 to V2.0 with "rs_" prefix, for those teams who have installed the V1.0 may install the V2.0 and the Apex methods calling the V1.0 without further refactoring will still call the V1.0 and the new Apex method will be built to call the V2.0.

I will assume that the new updates and fixes will be on the V2.0 only.

I will be happy to help with the refactoring if or when you decide to use one prefix.

Thank you for your consideration.

Regards,
Peter

**Comment by rsoesemann** [comment]
Not at the moment. Unlike the fflib this is not a wildly used framework but not more than a nicer PoC. Instead of people just using it I want them to fork it and contribute their improvements back.

The Github fork model also allows them to upgrade their forks (potentially even Unlocked packages) to new improvements I added. I also think before I add ugly prefixes I rather make this a Namespaced Unlocked Package.
